package models;

public enum TypeSegment {
	TYPE_NONE,
	TYPE_STRAIGHT_HORIZONTAL,
	TYPE_STRAIGHT_VERTICAL,
	TYPE_TURN_BOTTOM_TO_LEFT,
	TYPE_TURN_BOTTOM_TO_RIGHT,
	TYPE_TURN_TOP_TO_LEFT,
	TYPE_TURN_TOP_TO_RIGHT,
	TYPE_HARD_HORIZONTAL,
	TYPE_HARD_VERTICAL,
}
