
public enum TypeSegment {
	TYPE_STRAIGHT_HORIZONTAL,
	TYPE_STRAIGHT_VERTICAL,
	TYPE_TURN_BOTTOM_TO_LEFT,
	TYPE_TURN_BOTTOM_TO_RIGHT,
	TYPE_TURN_TOP_TO_LEFT,
	TYPE_TURN_TOP_TO_RIGHT,
	TYPE_TURN_MEDIUM_HORIZONTAL,
	TYPE_TURN_MEDIUM_VERTICAL,
	TYPE_TURN_HARD_HORIZONTAL,
	TYPE_TURN_HARD_VERTICAL
}
